name: gct-test

on:
  push:
    tags:
      - v*
    branches:
      - master
      - release
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --issues-exit-code=0 --timeout=10m

  test-unix:
    name: TestUnix
    needs: Lint
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Test
        run: go mod vendor && go test -v -mod=mod -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

  test-win:
    name: TestWindows
    needs: Lint
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Test
        run: go mod vendor && go test -v -mod=mod -race -coverprofile=coverageout -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: coverageout
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)